import React from "react";
import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Sakhaa Signal",
  description: "Terms of Service and AI Output Disclaimers for Sakhaa Signal SaaS Platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0B0A09] text-[#F3F2EF] font-sans flex flex-col justify-between">
      <header className="border-b border-[#2E2B26] py-6 px-6 max-w-7xl mx-auto w-full flex justify-between items-center">
        <Link href="/" className="text-lg font-bold text-[#F3F2EF]">Sakhaa Signal</Link>
        <Link href="/" className="text-sm text-[#7C70F6] hover:underline">&larr; Back to Home</Link>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12 flex-1 w-full space-y-8">
        <h1 className="text-3xl font-bold text-[#F3F2EF]">Terms of Service</h1>
        <p className="text-sm text-[#8A867C] font-mono">Last Updated: August 4, 2026</p>

        <section className="space-y-4 text-sm text-[#D4D1CA] leading-relaxed">
          <h2 className="text-xl font-semibold text-[#F3F2EF]">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Sakhaa Signal (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the application.
          </p>

          <h2 className="text-xl font-semibold text-[#F3F2EF]">2. AI & Neuromarketing Disclaimer</h2>
          <div className="p-4 rounded-md bg-[#1A1815] border border-[#FF6B3D]/30 text-[#FF6B3D] font-mono text-xs leading-relaxed">
            IMPORTANT: Sakhaa Signal scores (Emotional Pull, Visual Pull, Conversion Support, Brand Recall) and cortical cluster mappings (A–Q) are research-prior directional indicators generated by deep learning models. They assist creative decision-making but do not replace empirical media testing or guarantee specific ROAS/ad performance metrics.
          </div>

          <h2 className="text-xl font-semibold text-[#F3F2EF]">3. User Content & Upload Privacy</h2>
          <p>
            You retain ownership of all media, banners, and video assets uploaded to Sakhaa Signal. Uploaded assets are processed strictly to perform requested analysis jobs and are stored in private object storage in accordance with our Data Retention Policy.
          </p>
        </section>
      </main>

      <footer className="border-t border-[#2E2B26] py-6 text-center text-xs text-[#8A867C] font-mono">
        Sakhaa Signal Terms & Conditions
      </footer>
    </div>
  );
}
